//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace QLBanHang.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MainSoap", Namespace="http://tempuri.org/TransferData/Main")]
    public partial class Main : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOMOperationCompleted;
        
        private System.Threading.SendOrPostCallback PushDataSOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Main() {
            this.Url = global::QLBanHang.Properties.Settings.Default.QLBanHang_WebReference_Main;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataOMCompletedEventHandler GetDataOMCompleted;
        
        /// <remarks/>
        public event PushDataSOCompletedEventHandler PushDataSOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransferData/Main/GetDataOM", RequestNamespace="http://tempuri.org/TransferData/Main", ResponseNamespace="http://tempuri.org/TransferData/Main", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetDataOM(string OrgCode, string SubInvOrg, string LastDate, ref bool Success) {
            object[] results = this.Invoke("GetDataOM", new object[] {
                        OrgCode,
                        SubInvOrg,
                        LastDate,
                        Success});
            Success = ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataOMAsync(string OrgCode, string SubInvOrg, string LastDate, bool Success) {
            this.GetDataOMAsync(OrgCode, SubInvOrg, LastDate, Success, null);
        }
        
        /// <remarks/>
        public void GetDataOMAsync(string OrgCode, string SubInvOrg, string LastDate, bool Success, object userState) {
            if ((this.GetDataOMOperationCompleted == null)) {
                this.GetDataOMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOMOperationCompleted);
            }
            this.InvokeAsync("GetDataOM", new object[] {
                        OrgCode,
                        SubInvOrg,
                        LastDate,
                        Success}, this.GetDataOMOperationCompleted, userState);
        }
        
        private void OnGetDataOMOperationCompleted(object arg) {
            if ((this.GetDataOMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataOMCompleted(this, new GetDataOMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransferData/Main/PushDataSO", RequestNamespace="http://tempuri.org/TransferData/Main", ResponseNamespace="http://tempuri.org/TransferData/Main", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PushDataSO(string OrgCode, string SubInvOrg, string PriceListId, ref bool Success)
        {
            object[] results = this.Invoke("PushDataSO", new object[] {
                        OrgCode,
                        SubInvOrg,
                        PriceListId,
                        Success});
            Success = ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PushDataSOAsync(string OrgCode, string SubInvOrg, string PriceListId, bool Success)
        {
            this.PushDataSOAsync(OrgCode, SubInvOrg, PriceListId, Success, null);
        }
        
        /// <remarks/>
        public void PushDataSOAsync(string OrgCode, string SubInvOrg, string PriceListId, bool Success, object userState)
        {
            if ((this.PushDataSOOperationCompleted == null)) {
                this.PushDataSOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushDataSOOperationCompleted);
            }
            this.InvokeAsync("PushDataSO", new object[] {
                        OrgCode,
                        SubInvOrg,
                        PriceListId,
                        Success}, this.PushDataSOOperationCompleted, userState);
        }
        
        private void OnPushDataSOOperationCompleted(object arg) {
            if ((this.PushDataSOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushDataSOCompleted(this, new PushDataSOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetDataOMCompletedEventHandler(object sender, GetDataOMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataOMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataOMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void PushDataSOCompletedEventHandler(object sender, PushDataSOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushDataSOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushDataSOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Success {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591